In [2]:
import numpy as np

sales_data = np.array([
    [25000, 28000, 32000, 35000],
    [30000, 33000, 36000, 40000],
    [22000, 26000, 29000, 34000],
    [35000, 38000, 42000, 46000],
    [28000, 31000, 34000, 39000],
    [40000, 43000, 47000, 52000],
    [32000, 35000, 39000, 44000],
    [27000, 30000, 33000, 37000],
    [45000, 48000, 52000, 58000],
    [38000, 41000, 45000, 50000]
])

total_sales = np.sum(sales_data)

first_quarter_sales = np.sum(sales_data[:, 0])
fourth_quarter_sales = np.sum(sales_data[:, 3])

percentage_increase = (
    (fourth_quarter_sales - first_quarter_sales)
    / first_quarter_sales
) * 100

print("Quarterly Sales Data:")
print(sales_data)

print("\nTotal Sales for the Year:", total_sales)
print("First Quarter Sales:", first_quarter_sales)
print("Fourth Quarter Sales:", fourth_quarter_sales)
print("Percentage Increase from Q1 to Q4:", round(percentage_increase, 2), "%")

Quarterly Sales Data:
[[25000 28000 32000 35000]
 [30000 33000 36000 40000]
 [22000 26000 29000 34000]
 [35000 38000 42000 46000]
 [28000 31000 34000 39000]
 [40000 43000 47000 52000]
 [32000 35000 39000 44000]
 [27000 30000 33000 37000]
 [45000 48000 52000 58000]
 [38000 41000 45000 50000]]

Total Sales for the Year: 1499000
First Quarter Sales: 322000
Fourth Quarter Sales: 435000
Percentage Increase from Q1 to Q4: 35.09 %
